TICKER_SYMBOL = "GC=F"
ASSET_NAME = "Gold"
DATA_START_DATE = "2024-09-01"

# Indicator Settings
MA_SHORT = 20
MA_LONG = 50
RSI_PERIOD = 14
RSI_OVERBOUGHT = 70
RSI_OVERSOLD = 30

# Simulation Settings
REFRESH_RATE = 1.0  # Seconds between updates
INITIAL_STEP = 100